/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iMatPackage;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import se.chalmers.ait.dat215.project.IMatDataHandler;
import se.chalmers.ait.dat215.project.Product;
import se.chalmers.ait.dat215.project.ShoppingItem;

/**
 *
 * @author Alexander
 */
public class CartItem extends javax.swing.JPanel implements ChangeListener,ActionListener{

    /**
     * Creates new form CartItem
     */
    public CartItem(ShoppingItem item) {
        this.item = item;
        this.product = item.getProduct();
        initComponents();
        removeButton.addActionListener(this);
        priceSpinner.addChangeListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        priceSpinner = new javax.swing.JSpinner();
        unitLabel = new javax.swing.JLabel();
        removeButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(261, 41));
        setMinimumSize(new java.awt.Dimension(261, 41));
        setPreferredSize(new java.awt.Dimension(261, 41));

        nameLabel.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        nameLabel.setText(product.getName());
        nameLabel.setMaximumSize(new java.awt.Dimension(78, 13));
        nameLabel.setMinimumSize(new java.awt.Dimension(78, 13));
        nameLabel.setPreferredSize(new java.awt.Dimension(78, 13));

        priceSpinner.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        priceSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        priceSpinner.setToolTipText("Ändra Antalet av varan");
        priceSpinner.setMaximumSize(new java.awt.Dimension(38, 26));
        priceSpinner.setValue(item.getAmount());

        unitLabel.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        unitLabel.setText(new Double(item.getTotal()).toString() + " kr");
        unitLabel.setMaximumSize(new java.awt.Dimension(48, 13));
        unitLabel.setMinimumSize(new java.awt.Dimension(48, 13));
        unitLabel.setPreferredSize(new java.awt.Dimension(48, 13));

        removeButton.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        removeButton.setText("X");
        removeButton.setMaximumSize(new java.awt.Dimension(42, 29));
        removeButton.setMinimumSize(new java.awt.Dimension(42, 29));
        removeButton.setPreferredSize(new java.awt.Dimension(42, 29));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );
    }// </editor-fold>//GEN-END:initComponents
    @Override
    public void actionPerformed(ActionEvent e){
        if(e.getSource() == removeButton){
            IMatDataHandler.getInstance().getShoppingCart().removeItem(item);
        }
    }

    @Override
    public void stateChanged(ChangeEvent e) {
        item.setAmount(((Integer)(priceSpinner.getValue())).doubleValue());
        priceLabel.setText(priceSpinner.getValue().toString());
        IMatDataHandler.getInstance().getShoppingCart().fireShoppingCartChanged(item, true);
    }
    
    public Product getProduct(){
        return product;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nameLabel;
    private javax.swing.JSpinner priceSpinner;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel unitLabel;
    // End of variables declaration//GEN-END:variables
    private ShoppingItem item;
    private Product product;

    

}
