/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iMatPackage;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JPanel;

/**
 *
 * @author Alexander
 */
public class CategoryPanel extends javax.swing.JPanel implements MouseListener{
    
    private JPanel main;
    private JPanel sub;
    private Category categorie;
    private CardLayout cardManager;

    /**
     * Creates new form CategoriePanel
     */
    public CategoryPanel(Category c) {
        initComponents();
        setLayout(new CardLayout());
        cardManager = (CardLayout)getLayout();
        categorie = c;
        this.main = new MainCategoryPanel(categorie);
        main.addMouseListener(this);
        this.sub = new SubCategoryPanel(categorie.getSubCategories());
        add(sub);
        add(main);
        cardManager.addLayoutComponent("Sub", sub);
        cardManager.addLayoutComponent("Main", main);
        cardManager.show(this, "Main");
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void reset(){
        categorie.unChoose();
        updateView();
    }
    
    public void updateView(){
        if(categorie.isChosen()){
            cardManager.show(this, "Sub");
        }else{
            cardManager.show(this, "Sub");
        }
        repaint();
        revalidate();
    }
    
    @Override
    public void mouseClicked(MouseEvent e) {
        CategoryController.resetCategoriePanels();
        categorie.choose();
        updateView();
    }

    @Override
    public void mousePressed(MouseEvent e) {}

    @Override
    public void mouseReleased(MouseEvent e) {}

    @Override
    public void mouseEntered(MouseEvent e) {}

    @Override
    public void mouseExited(MouseEvent e) {}
}
