/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iMatPackage;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JPanel;

/**
 *
 * @author Alexander
 */
public class CategoryPanel extends javax.swing.JPanel implements MouseListener{
    
    private JPanel main;
    private JPanel sub;
    private JPanel currentlyDisplaying;
    private Category categorie;

    /**
     * Creates new form CategoriePanel
     */
    public CategoryPanel(Category c) {
        categorie = c;
        this.main = new MainCategoryPanel(categorie);
        this.sub = new SubCategoryPanel(categorie.getSubCategories());
        currentlyDisplaying = main;
        add(currentlyDisplaying);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void reset(){
        categorie.unChoose();
    }
    
    public void updateView(){
        if(categorie.isChosen()){
            currentlyDisplaying = sub;
        }else{
            currentlyDisplaying = main;
        }
        repaint();
    }
    
    @Override
    public void mouseClicked(MouseEvent e) {
        if(e.getSource() == main){
            CategoryController.resetCategoriePanels();
            categorie.choose();
            updateView();
            
            
        }
    }

    @Override
    public void mousePressed(MouseEvent e) {}

    @Override
    public void mouseReleased(MouseEvent e) {}

    @Override
    public void mouseEntered(MouseEvent e) {}

    @Override
    public void mouseExited(MouseEvent e) {}
}
