/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iMatPackage;

import javax.swing.JPanel;
import javax.swing.JTextField;
import se.chalmers.ait.dat215.project.Order;
import se.chalmers.ait.dat215.project.ShoppingItem;

/**
 *
 * @author Poya
 */
public class ItemInfoPanel extends javax.swing.JPanel {

    private Order order;
    
    
    public ItemInfoPanel(Order o) {
        initComponents();
        this.order = o;
        
    }
    
    public double getOrderTotal(){
        double temp = 0;
      for(ShoppingItem x : order.getItems()){
          temp = temp + x.getTotal();
      }  
      return temp;
    }
    
    public double getOrderAmount(){
        double temp = 0;
      for(ShoppingItem x : order.getItems()){
          temp = temp + x.getAmount();
      }  
      return temp;
    }
    
    public void listOrderInfo(){
        for(int i = 0; i < order.getItems().size(); i++){
            itemInfoPanel.add(new JTextField(order.getItems().get(i).getProduct().getName()));
            itemInfoPanel.add(new JTextField("" + order.getItems().get(i).getAmount()));
            itemInfoPanel.add(new JTextField("" + order.getItems().get(i).getTotal()));
        }
        
        itemInfoPanel.add(new JTextField(""));
        itemInfoPanel.add(new JTextField("" + getOrderAmount()));
        itemInfoPanel.add(new JTextField("" + getOrderTotal()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemInfoPanel = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout(0, 1));

        itemInfoPanel.setLayout(new java.awt.GridLayout(0, 3));
        add(itemInfoPanel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel itemInfoPanel;
    // End of variables declaration//GEN-END:variables
}
