/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iMatPackage;

/**
 *
 * @author Poya
 */
public class LeftBrowseView extends javax.swing.JPanel {

    /**
     * Creates new form LeftBrowseView
     */
    public LeftBrowseView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftpanel = new javax.swing.JPanel();
        meatAndFishButton = new javax.swing.JButton();
        dairyButton = new javax.swing.JButton();
        fruitVegetableButton = new javax.swing.JButton();
        RiceAndPastaButton = new javax.swing.JButton();
        SpiceButton = new javax.swing.JButton();
        BakingAndBreadButton = new javax.swing.JButton();
        frozenFoodButton = new javax.swing.JButton();
        beveragesButton = new javax.swing.JButton();
        SweetsButton = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();

        meatAndFishButton.setText("Kött & Fisk");
        meatAndFishButton.setBorder(null);
        meatAndFishButton.setContentAreaFilled(false);

        dairyButton.setText("Mejeri");
        dairyButton.setBorder(null);
        dairyButton.setContentAreaFilled(false);
        dairyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dairyButtonActionPerformed(evt);
            }
        });

        fruitVegetableButton.setText("Frukt & Grönt");
        fruitVegetableButton.setBorder(null);
        fruitVegetableButton.setContentAreaFilled(false);

        RiceAndPastaButton.setText("Ris & Pasta");
        RiceAndPastaButton.setBorder(null);
        RiceAndPastaButton.setContentAreaFilled(false);

        SpiceButton.setText("Kryddor");
        SpiceButton.setBorder(null);
        SpiceButton.setContentAreaFilled(false);

        BakingAndBreadButton.setText("Bakning & Bröd");
        BakingAndBreadButton.setBorder(null);
        BakingAndBreadButton.setContentAreaFilled(false);

        frozenFoodButton.setText("Frysdisk");
        frozenFoodButton.setBorder(null);
        frozenFoodButton.setContentAreaFilled(false);
        frozenFoodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frozenFoodButtonActionPerformed(evt);
            }
        });

        beveragesButton.setText("Drycker");
        beveragesButton.setBorder(null);
        beveragesButton.setContentAreaFilled(false);

        SweetsButton.setText("Godis & Chips");
        SweetsButton.setBorder(null);
        SweetsButton.setContentAreaFilled(false);

        javax.swing.GroupLayout leftpanelLayout = new javax.swing.GroupLayout(leftpanel);
        leftpanel.setLayout(leftpanelLayout);
        leftpanelLayout.setHorizontalGroup(
            leftpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(meatAndFishButton)
                    .addComponent(RiceAndPastaButton)
                    .addComponent(SpiceButton)
                    .addComponent(frozenFoodButton)
                    .addComponent(beveragesButton)
                    .addComponent(BakingAndBreadButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dairyButton)
                    .addComponent(fruitVegetableButton)
                    .addComponent(jSeparator14)
                    .addComponent(SweetsButton)
                    .addComponent(jSeparator13)
                    .addComponent(jSeparator12)
                    .addComponent(jSeparator11)
                    .addComponent(jSeparator10)
                    .addComponent(jSeparator9)
                    .addComponent(jSeparator8)
                    .addComponent(jSeparator7)
                    .addComponent(jSeparator6))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        leftpanelLayout.setVerticalGroup(
            leftpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(meatAndFishButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(dairyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fruitVegetableButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RiceAndPastaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SpiceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BakingAndBreadButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(frozenFoodButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(beveragesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(SweetsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(leftpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(leftpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dairyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dairyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dairyButtonActionPerformed

    private void frozenFoodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frozenFoodButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frozenFoodButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BakingAndBreadButton;
    private javax.swing.JButton RiceAndPastaButton;
    private javax.swing.JButton SpiceButton;
    private javax.swing.JButton SweetsButton;
    private javax.swing.JButton beveragesButton;
    private javax.swing.JButton dairyButton;
    private javax.swing.JButton frozenFoodButton;
    private javax.swing.JButton fruitVegetableButton;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel leftpanel;
    private javax.swing.JButton meatAndFishButton;
    // End of variables declaration//GEN-END:variables
}
