/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iMatPackage;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.LayoutManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JPanel;
import se.chalmers.ait.dat215.project.IMatDataHandler;

/**
 *
 * @author Alexander
 */
public class MainWindow extends javax.swing.JFrame {
    
    private static CartWizardView cartWizardView;
    private static PaymentWizardView paymentWizardView;
    private static StoreView storeView;
    private static InformationChooseView informationChooseView;
    private static InformationGuestView informationGuestView;
    private static InformationUserView informationUserView;
    private static InformationRegisterView informationRegisterView;
    private static CardLayout cardManager;
    

    /**
     * Creates new form MainController
     */
    public MainWindow() {
        cartWizardView = new CartWizardView();
        paymentWizardView = new PaymentWizardView();
        storeView = new StoreView();
        informationChooseView = new InformationChooseView();
        informationGuestView = new InformationGuestView();
        informationUserView = new InformationUserView();
        informationRegisterView = new InformationRegisterView();
        
        initComponents();
        cardManager = (CardLayout)cardPanel.getLayout();
        
        
        
        cardPanel.add(cartWizardView);
        cardPanel.add(storeView);
        cardPanel.add(informationChooseView);
        cardPanel.add(informationUserView);
        cardPanel.add(informationGuestView);
        cardPanel.add(informationUserView);
        cardPanel.add(informationRegisterView);
        cardPanel.add(paymentWizardView);
        
        cardManager.addLayoutComponent("StoreView", storeView);
        cardManager.addLayoutComponent("CartWizardView", cartWizardView);
        cardManager.addLayoutComponent("InformationChooseView", informationChooseView);
        cardManager.addLayoutComponent("InformationUserView", informationUserView);
        cardManager.addLayoutComponent("InformationGuestView", informationGuestView);
        cardManager.addLayoutComponent("InformationRegisterView", informationRegisterView);
        cardManager.addLayoutComponent("PaymentWizardView", paymentWizardView);
        cardManager.show(cardPanel, "StoreView");
        
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setPreferredSize(new Dimension(1200,700));
        setLocationRelativeTo(null);
        
    }
    
    public static void showStoreView(){
        cardManager.show(cardPanel, "StoreView");
    }
    public static void showCartWizardView(){
        cardManager.show(cardPanel, "CartWizardView" );
    }
    public static void showInformationChooseView(){
        cardManager.show(cardPanel, "InformationChooseView");
    }
    public static void showInformationUserView(){
        cardManager.show(cardPanel, "InformationUserView");
    }
    public static void showInformationGuestView(){
        cardManager.show(cardPanel, "InformationGuestView");
    }
    public static void showInformationRegisterView(){
        cardManager.show(cardPanel, "InformationRegisterView");
    }
    public static void paymentWizardView(){
        cardManager.show(cardPanel, "PaymentWizardView");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        cardPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(cardPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        IMatDataHandler.getInstance().shutDown();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JPanel cardPanel;
    // End of variables declaration//GEN-END:variables

}
