/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iMatPackage;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import se.chalmers.ait.dat215.project.IMatDataHandler;
import se.chalmers.ait.dat215.project.Order;

/**
 *
 * @author Poya
 */
public class OrderHistoryView extends javax.swing.JPanel{

    private  static List<Order> orders;
    
    
    
    public OrderHistoryView() {
        initComponents();
        
        //orders = backend.getOrders();
    }
    
    public static void importOrders(){
        //orders = backend.getOrders();
        orderIDPanel.removeAll();
        for(Order e: IMatDataHandler.getInstance().getOrders()){
            orderIDPanel.add(new OrderItemButton(e));
        }
        orderIDPanel.repaint();
    }
    public static void clearOrderList(){
        orderResultPanel.removeAll();
        orderResultPanel.repaint();
        
    }
    
    public static void showOrderInfo(Order e){
        ItemInfoPanel itemInfo = new ItemInfoPanel(e);
        
        orderResultPanel.removeAll();
        
        orderResultPanel.add(itemInfo);
        itemInfo.listOrderInfo();
        
        orderResultPanel.repaint();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderIDPane = new javax.swing.JScrollPane();
        orderIDPanel = new javax.swing.JPanel();
        orderResultScrollPane = new javax.swing.JScrollPane();
        orderResultPanel = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        orderHistoryLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(207, 219, 231));

        orderIDPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        orderIDPanel.setBackground(new java.awt.Color(255, 255, 255));
        orderIDPanel.setLayout(new java.awt.GridLayout(0, 1));
        orderIDPane.setViewportView(orderIDPanel);

        orderResultScrollPane.setBackground(new java.awt.Color(51, 153, 255));

        orderResultPanel.setBackground(new java.awt.Color(255, 255, 255));
        orderResultPanel.setPreferredSize(new java.awt.Dimension(270, 200));
        orderResultPanel.setLayout(new java.awt.GridLayout(0, 1));
        orderResultScrollPane.setViewportView(orderResultPanel);

        backButton.setBackground(new java.awt.Color(51, 153, 255));
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Tillbaka");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        orderHistoryLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        orderHistoryLabel.setText("OrderHistorik");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(orderIDPane, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(orderResultScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(orderHistoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(223, 223, 223))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(orderHistoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(orderResultScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 52, Short.MAX_VALUE))
                    .addComponent(orderIDPane))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        MainWindow.showStoreView();
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel orderHistoryLabel;
    private javax.swing.JScrollPane orderIDPane;
    private static javax.swing.JPanel orderIDPanel;
    private static javax.swing.JPanel orderResultPanel;
    private javax.swing.JScrollPane orderResultScrollPane;
    // End of variables declaration//GEN-END:variables

    
}
