/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iMatPackage;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import se.chalmers.ait.dat215.project.Order;

/**
 *
 * @author Poya
 */
public class OrderItemButton extends javax.swing.JPanel implements ActionListener {

    private Order order;
    private ItemInfoPanel itemInfoPanel;
    
    public OrderItemButton(Order e) {
        initComponents();
        this.order = e;
        this.itemInfoPanel = new ItemInfoPanel(e);
        orderIDButton.setText("#" + e.getOrderNumber());
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        
        OrderHistoryView.clearOrderList();
        itemInfoPanel.listOrderInfo();
    }
    
    public ItemInfoPanel getItemInfoPanel(){
        return itemInfoPanel;
    }
    
    public Order getOrder(){
        return order;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderIDButton = new javax.swing.JButton();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(orderIDButton, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(orderIDButton))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton orderIDButton;
    // End of variables declaration//GEN-END:variables

    
}
